name = "Coder-Timeline"
license = "MIT"
licenselink = "https://github.com/13hannes11/hugo-coder-timeline/blob/master/LICENSE.md"
description = "An extenison for the theme Coder simple and clean blog theme for Hugo"
homepage = "https://github.com/13hannes11/hugo-coder-timeline/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "Hannes Kuchelmeister"
homepage = "https://hanneskuchelmeister.de"

